version: '3.8'

services:
  app:
    image: kimsee/allrealmen:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
    networks:
      - allReal_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth
    networks:
      - allReal_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - allReal_network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  allReal_network:
    name: allReal_network


