version: '3.8'

services:
  app:
    image: kimsee/allrealmen:latest
    ports:
      - "8080:8080"
    environment:
      # MongoDB 설정
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/allrealmen?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=allrealmen
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true

      # JPA 설정
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect

      # Multipart 설정
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB

      # OAuth2 Naver 설정
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_NAME=naver
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_AUTHORIZATION_GRANT_TYPE=authorization_code
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_SCOPE=name,email
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI=${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/naver

      # OAuth2 Google 설정
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_NAME=google
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE=authorization_code
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE=profile,email
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI=${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/google

      # OAuth2 Kakao 설정
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_NAME=kakao
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE=authorization_code
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_AUTHENTICATION_METHOD=client_secret_post
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE=profile_nickname,account_email
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI=${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/kakao

      # OAuth2 Provider 설정
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_PROVIDER_AUTHORIZATION_URI=https://kauth.kakao.com/oauth/authorize
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_PROVIDER_TOKEN_URI=https://kauth.kakao.com/oauth/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_PROVIDER_USER_INFO_URI=https://kapi.kakao.com/v2/user/me
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_PROVIDER_USER_NAME_ATTRIBUTE=id

      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_PROVIDER_AUTHORIZATION_URI=https://nid.naver.com/oauth2.0/authorize
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_PROVIDER_TOKEN_URI=https://nid.naver.com/oauth2.0/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_PROVIDER_USER_INFO_URI=https://openapi.naver.com/v1/nid/me
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_NAVER_PROVIDER_USER_NAME_ATTRIBUTE=response

      # JWT 설정
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration=3600000
      - jwt.access-token-validity=3600000
      - jwt.refresh-token-validity=604800000

      # Naver Cloud 설정
      - naver-cloud.sms.access-key=${NAVER_CLOUD_ACCESS_KEY}
      - naver-cloud.sms.secret-key=${NAVER_CLOUD_SECRET_KEY}
      - naver-cloud.sms.service-id=${NAVER_CLOUD_SERVICE_ID}
      - naver-cloud.sms.sender-phone=${NAVER_CLOUD_SENDER_PHONE}

      # 로깅 설정
      - logging.level.org.springframework.data.mongodb=DEBUG

      # 서버 설정
      - SERVER_PORT=8080

      # Kakao API 설정
      - kakao.api.admin-key=${KAKAO_ADMIN_KEY}
      - kakao.api.template-id=${KAKAO_TEMPLATE_ID}

      # 프로필 설정
      - SPRING_PROFILES_ACTIVE=prod

    volumes:
      - ./config:/app/config

    depends_on:
      - mongodb
    networks:
      - allReal_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - allReal_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - allReal_network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  allReal_network:
    name: allReal_network


