naver-cloud:
  sms:
    access-key: ${NAVER_CLOUD_ACCESS_KEY}
    secret-key: ${NAVER_CLOUD_SECRET_KEY}
    service-id: ${NAVER_CLOUD_SERVICE_ID}
    sender-phone: ${NAVER_CLOUD_SENDER_PHONE}

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: allrealmen
#      username: ${MONGO_INITDB_ROOT_USERNAME}
#      password: ${MONGO_INITDB_ROOT_PASSWORD}
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/api/auth/oauth2/callback/naver
            provider: naver-provider
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/api/auth/oauth2/callback/google
            provider: google

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/api/auth/oauth2/callback/kakao
            provider: kakao-provider

        provider:
          kakao-provider:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver-provider:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.example.allrealmen: DEBUG

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24시간

kakao:
  api:
    admin-key: ${KAKAO_ADMIN_KEY}
    template-id: ${KAKAO_TEMPLATE_ID}

